<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grepc_client.proto

namespace GrpcServices;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpcServices.GrpcRequest</code>
 */
class GrpcRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string fieldOne = 1;</code>
     */
    protected $fieldOne = '';
    /**
     * Generated from protobuf field <code>bool fieldTwo = 2;</code>
     */
    protected $fieldTwo = false;
    /**
     * Generated from protobuf field <code>int32 fieldThree = 3;</code>
     */
    protected $fieldThree = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $fieldOne
     *     @type bool $fieldTwo
     *     @type int $fieldThree
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrepcClient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string fieldOne = 1;</code>
     * @return string
     */
    public function getFieldOne()
    {
        return $this->fieldOne;
    }

    /**
     * Generated from protobuf field <code>string fieldOne = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldOne($var)
    {
        GPBUtil::checkString($var, True);
        $this->fieldOne = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool fieldTwo = 2;</code>
     * @return bool
     */
    public function getFieldTwo()
    {
        return $this->fieldTwo;
    }

    /**
     * Generated from protobuf field <code>bool fieldTwo = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setFieldTwo($var)
    {
        GPBUtil::checkBool($var);
        $this->fieldTwo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 fieldThree = 3;</code>
     * @return int
     */
    public function getFieldThree()
    {
        return $this->fieldThree;
    }

    /**
     * Generated from protobuf field <code>int32 fieldThree = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setFieldThree($var)
    {
        GPBUtil::checkInt32($var);
        $this->fieldThree = $var;

        return $this;
    }

}

